const container = {
  CONTAINER_PADDING_X: '20px',
  CONTAINER_PADDING_X_MD: '50px',
};

const VAR = {
  BREAKPOINTS_XS: 375,
  BREAKPOINTS_SM: 576,
  BREAKPOINTS_MD: 768,
  BREAKPOINTS_LG: 992,
  BREAKPOINTS_XL: 1280,
  BREAKPOINTS_2XL: 1400,
  BREAKPOINTS_3XL: 1600,
  BREAKPOINTS_4XL: 1780,
  ...container,
};
export default VAR;
