export const fontsPreload: any = [
  {
    rel: 'preload',
    href: '/fonts/poppins/Poppins-Thin.ttf',
    as: 'font' as const,
    type: 'font/ttf',
    crossorigin: 'anonymous',
  },
  {
    rel: 'preload',
    href: '/fonts/poppins/Poppins-ExtraLight.ttf',
    as: 'font' as const,
    type: 'font/ttf',
    crossorigin: 'anonymous',
  },
  {
    rel: 'preload',
    href: '/fonts/poppins/Poppins-Light.ttf',
    as: 'font' as const,
    type: 'font/ttf',
    crossorigin: 'anonymous',
  },
  {
    rel: 'preload',
    href: '/fonts/poppins/Poppins-Regular.ttf',
    as: 'font' as const,
    type: 'font/ttf',
    crossorigin: 'anonymous',
  },
  {
    rel: 'preload',
    href: '/fonts/poppins/Poppins-Medium.ttf',
    as: 'font' as const,
    type: 'font/ttf',
    crossorigin: 'anonymous',
  },
  {
    rel: 'preload',
    href: '/fonts/poppins/Poppins-SemiBold.ttf',
    as: 'font' as const,
    type: 'font/ttf',
    crossorigin: 'anonymous',
  },
  {
    rel: 'preload',
    href: '/fonts/poppins/Poppins-Bold.ttf',
    as: 'font' as const,
    type: 'font/ttf',
    crossorigin: 'anonymous',
  },
  {
    rel: 'preload',
    href: '/fonts/poppins/Poppins-ExtraBold.ttf',
    as: 'font' as const,
    type: 'font/ttf',
    crossorigin: 'anonymous',
  },
  {
    rel: 'preload',
    href: '/fonts/poppins/Poppins-Black.ttf',
    as: 'font' as const,
    type: 'font/ttf',
    crossorigin: 'anonymous',
  },
  {
    rel: 'preload',
    href: '/fonts/poppins/Poppins-ThinItalic.ttf',
    as: 'font' as const,
    type: 'font/ttf',
    crossorigin: 'anonymous',
  },
  {
    rel: 'preload',
    href: '/fonts/poppins/Poppins-ExtraLightItalic.ttf',
    as: 'font' as const,
    type: 'font/ttf',
    crossorigin: 'anonymous',
  },
  {
    rel: 'preload',
    href: '/fonts/poppins/Poppins-LightItalic.ttf',
    as: 'font' as const,
    type: 'font/ttf',
    crossorigin: 'anonymous',
  },
  {
    rel: 'preload',
    href: '/fonts/poppins/Poppins-Italic.ttf',
    as: 'font' as const,
    type: 'font/ttf',
    crossorigin: 'anonymous',
  },
  {
    rel: 'preload',
    href: '/fonts/poppins/Poppins-MediumItalic.ttf',
    as: 'font' as const,
    type: 'font/ttf',
    crossorigin: 'anonymous',
  },
  {
    rel: 'preload',
    href: '/fonts/poppins/Poppins-SemiBoldItalic.ttf',
    as: 'font' as const,
    type: 'font/ttf',
    crossorigin: 'anonymous',
  },
  {
    rel: 'preload',
    href: '/fonts/poppins/Poppins-BoldItalic.ttf',
    as: 'font' as const,
    type: 'font/ttf',
    crossorigin: 'anonymous',
  },
  {
    rel: 'preload',
    href: '/fonts/poppins/Poppins-ExtraBoldItalic.ttf',
    as: 'font' as const,
    type: 'font/ttf',
    crossorigin: 'anonymous',
  },
  {
    rel: 'preload',
    href: '/fonts/poppins/Poppins-BlackItalic.ttf',
    as: 'font' as const,
    type: 'font/ttf',
    crossorigin: 'anonymous',
  },
  {
    rel: 'preload',
    href: '/fonts/orbitron/static/Orbitron-Regular.ttf',
    as: 'font' as const,
    type: 'font/ttf',
    crossorigin: 'anonymous',
  },
  {
    rel: 'preload',
    href: '/fonts/orbitron/static/Orbitron-Medium.ttf',
    as: 'font' as const,
    type: 'font/ttf',
    crossorigin: 'anonymous',
  },
  {
    rel: 'preload',
    href: '/fonts/orbitron/static/Orbitron-SemiBold.ttf',
    as: 'font' as const,
    type: 'font/ttf',
    crossorigin: 'anonymous',
  },
  {
    rel: 'preload',
    href: '/fonts/orbitron/static/Orbitron-Bold.ttf',
    as: 'font' as const,
    type: 'font/ttf',
    crossorigin: 'anonymous',
  },
  {
    rel: 'preload',
    href: '/fonts/orbitron/static/Orbitron-ExtraBold.ttf',
    as: 'font' as const,
    type: 'font/ttf',
    crossorigin: 'anonymous',
  },
  {
    rel: 'preload',
    href: '/fonts/orbitron/static/Orbitron-Black.ttf',
    as: 'font' as const,
    type: 'font/ttf',
    crossorigin: 'anonymous',
  },
  {
    rel: 'preload',
    href: '/fonts/stick_no_bills/static/StickNoBills-Regular.ttf',
    as: 'font' as const,
    type: 'font/ttf',
    crossorigin: 'anonymous',
  },
  {
    rel: 'preload',
    href: '/fonts/stick_no_bills/static/StickNoBills-Medium.ttf',
    as: 'font' as const,
    type: 'font/ttf',
    crossorigin: 'anonymous',
  },
  {
    rel: 'preload',
    href: '/fonts/stick_no_bills/static/StickNoBills-SemiBold.ttf',
    as: 'font' as const,
    type: 'font/ttf',
    crossorigin: 'anonymous',
  },
  {
    rel: 'preload',
    href: '/fonts/stick_no_bills/static/StickNoBills-Bold.ttf',
    as: 'font' as const,
    type: 'font/ttf',
    crossorigin: 'anonymous',
  },
  {
    rel: 'preload',
    href: '/fonts/stick_no_bills/static/StickNoBills-ExtraBold.ttf',
    as: 'font' as const,
    type: 'font/ttf',
    crossorigin: 'anonymous',
  },
];
