export const fontsPreload: any = [
  {
    rel: 'preload',
    href: '/fonts/montserrat/static/Montserrat-Thin.ttf',
    as: 'font' as const,
    type: 'font/ttf',
    crossorigin: 'anonymous',
  },
  {
    rel: 'preload',
    href: '/fonts/montserrat/static/Montserrat-ExtraLight.ttf',
    as: 'font' as const,
    type: 'font/ttf',
    crossorigin: 'anonymous',
  },
  {
    rel: 'preload',
    href: '/fonts/montserrat/static/Montserrat-Light.ttf',
    as: 'font' as const,
    type: 'font/ttf',
    crossorigin: 'anonymous',
  },
  {
    rel: 'preload',
    href: '/fonts/montserrat/static/Montserrat-Regular.ttf',
    as: 'font' as const,
    type: 'font/ttf',
    crossorigin: 'anonymous',
  },
  {
    rel: 'preload',
    href: '/fonts/montserrat/static/Montserrat-Medium.ttf',
    as: 'font' as const,
    type: 'font/ttf',
    crossorigin: 'anonymous',
  },
  {
    rel: 'preload',
    href: '/fonts/montserrat/static/Montserrat-SemiBold.ttf',
    as: 'font' as const,
    type: 'font/ttf',
    crossorigin: 'anonymous',
  },
  {
    rel: 'preload',
    href: '/fonts/montserrat/static/Montserrat-Bold.ttf',
    as: 'font' as const,
    type: 'font/ttf',
    crossorigin: 'anonymous',
  },
  {
    rel: 'preload',
    href: '/fonts/montserrat/static/Montserrat-ExtraBold.ttf',
    as: 'font' as const,
    type: 'font/ttf',
    crossorigin: 'anonymous',
  },
  {
    rel: 'preload',
    href: '/fonts/montserrat/static/Montserrat-Black.ttf',
    as: 'font' as const,
    type: 'font/ttf',
    crossorigin: 'anonymous',
  },
  {
    rel: 'preload',
    href: '/fonts/montserrat/static/Montserrat-ThinItalic.ttf',
    as: 'font' as const,
    type: 'font/ttf',
    crossorigin: 'anonymous',
  },
  {
    rel: 'preload',
    href: '/fonts/montserrat/static/Montserrat-ExtraLightItalic.ttf',
    as: 'font' as const,
    type: 'font/ttf',
    crossorigin: 'anonymous',
  },
  {
    rel: 'preload',
    href: '/fonts/montserrat/static/Montserrat-LightItalic.ttf',
    as: 'font' as const,
    type: 'font/ttf',
    crossorigin: 'anonymous',
  },
  {
    rel: 'preload',
    href: '/fonts/montserrat/static/Montserrat-Italic.ttf',
    as: 'font' as const,
    type: 'font/ttf',
    crossorigin: 'anonymous',
  },
  {
    rel: 'preload',
    href: '/fonts/montserrat/static/Montserrat-MediumItalic.ttf',
    as: 'font' as const,
    type: 'font/ttf',
    crossorigin: 'anonymous',
  },
  {
    rel: 'preload',
    href: '/fonts/montserrat/static/Montserrat-SemiBoldItalic.ttf',
    as: 'font' as const,
    type: 'font/ttf',
    crossorigin: 'anonymous',
  },
  {
    rel: 'preload',
    href: '/fonts/montserrat/static/Montserrat-BoldItalic.ttf',
    as: 'font' as const,
    type: 'font/ttf',
    crossorigin: 'anonymous',
  },
  {
    rel: 'preload',
    href: '/fonts/montserrat/static/Montserrat-ExtraBoldItalic.ttf',
    as: 'font' as const,
    type: 'font/ttf',
    crossorigin: 'anonymous',
  },
  {
    rel: 'preload',
    href: '/fonts/montserrat/static/Montserrat-BlackItalic.ttf',
    as: 'font' as const,
    type: 'font/ttf',
    crossorigin: 'anonymous',
  },
  {
    rel: 'preload',
    href: '/fonts/orbitron/static/Orbitron-Regular.ttf',
    as: 'font' as const,
    type: 'font/ttf',
    crossorigin: 'anonymous',
  },
  {
    rel: 'preload',
    href: '/fonts/orbitron/static/Orbitron-Medium.ttf',
    as: 'font' as const,
    type: 'font/ttf',
    crossorigin: 'anonymous',
  },
  {
    rel: 'preload',
    href: '/fonts/orbitron/static/Orbitron-SemiBold.ttf',
    as: 'font' as const,
    type: 'font/ttf',
    crossorigin: 'anonymous',
  },
  {
    rel: 'preload',
    href: '/fonts/orbitron/static/Orbitron-Bold.ttf',
    as: 'font' as const,
    type: 'font/ttf',
    crossorigin: 'anonymous',
  },
  {
    rel: 'preload',
    href: '/fonts/orbitron/static/Orbitron-ExtraBold.ttf',
    as: 'font' as const,
    type: 'font/ttf',
    crossorigin: 'anonymous',
  },
  {
    rel: 'preload',
    href: '/fonts/orbitron/static/Orbitron-Black.ttf',
    as: 'font' as const,
    type: 'font/ttf',
    crossorigin: 'anonymous',
  },
  {
    rel: 'preload',
    href: '/fonts/stick_no_bills/static/StickNoBills-Regular.ttf',
    as: 'font' as const,
    type: 'font/ttf',
    crossorigin: 'anonymous',
  },
  {
    rel: 'preload',
    href: '/fonts/stick_no_bills/static/StickNoBills-Medium.ttf',
    as: 'font' as const,
    type: 'font/ttf',
    crossorigin: 'anonymous',
  },
  {
    rel: 'preload',
    href: '/fonts/stick_no_bills/static/StickNoBills-SemiBold.ttf',
    as: 'font' as const,
    type: 'font/ttf',
    crossorigin: 'anonymous',
  },
  {
    rel: 'preload',
    href: '/fonts/stick_no_bills/static/StickNoBills-Bold.ttf',
    as: 'font' as const,
    type: 'font/ttf',
    crossorigin: 'anonymous',
  },
  {
    rel: 'preload',
    href: '/fonts/stick_no_bills/static/StickNoBills-ExtraBold.ttf',
    as: 'font' as const,
    type: 'font/ttf',
    crossorigin: 'anonymous',
  },
];
